## Server Properties
server:
  port: 5000

  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sco_db
    username: root
    password:
    initialization-mode: always

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    hibernate.ddl-auto: update
  ## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC



  ## Hibernate Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000

